style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: "https://gitlab.bluetab.net/terraform/modules/google/gcp-bigquery"
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
